version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "8010:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: webmaybom
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
